config/routes.rb
Krew::Application.routes.draw do
  resources :groups do
    resources :relationships
  end
  resources :users
  get 'sign_in', to: 'sessions#new', as: "sign_in"
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  root to: "home#index"
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :interests
  belongs_to :admin, class_name: "User"
  has_many :relationships, foreign_key: "liker_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "liked_id", class_name: "Relationship"
  has_many :likes, through: :relationships
  has_many :likers, through: :reverse_relationships
  has_many :group_invites
  belongs_to :location

  validates :name, :tagline, :gender, :seeking_gender, :location_id, :start_date, :end_date, presence: true
  validate :validate_trip_date, if: "start_date.present? && end_date.present?"

  attr_accessor :user_uids

  def admin?(user)
    user.id == admin.id
  end

  def like!(group)
    relationships.create!(liked_id: group.id, like: true)
  end

  def dislike!(group)
    relationships.create!(liked_id: group.id, like: false)
  end

  def likes?(group)
    relationships.where(liked_id: group.id, like: true).count == 1
  end

private

  def validate_trip_date
    errors.add(:trip_date, "is invalid") if 1.day.from_now > start_date || end_date < start_date
  end

end

app/models/group_invite.rb
class GroupInvite < ActiveRecord::Base
  belongs_to :group
  belongs_to :user

  validates :user, :group, presence: true

  def accept!
    group.users << user
    self.delete
  end

  def decline!
    group.delete
  end
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :location
  has_and_belongs_to_many :groups
end

app/models/location.rb
class Location < ActiveRecord::Base

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :liker, class_name: "Group"
  belongs_to :liked, class_name: "Group"
  validates :liker_id, presence: true
  validates :liked_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :groups
  has_many :group_invites, dependent: :destroy

  validates :provider, :uid, presence: true

  def self.from_provider_and_uid(provider, uid)
    where(provider: provider, uid: uid).first_or_initialize.tap do |user|
      user.provider = provider
      user.uid = uid
      user.save!
    end
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.birthday = auth.extra.raw_info.birthday
      user.gender = auth.extra.raw_info.gender
      user.location = auth.info.location
      user.available = !auth.extra.raw_info.significant_other.present?
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def profile_picture_large
    "https://graph.facebook.com/#{uid}/picture?width=300&height=300"
  end

  def available_text
    available? ? "Available" : "Unavailable"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  private

  def authenticate_user!
    unless current_user
      render "sessions/new"
      return
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new(params[:group])
    @group.user_uids = []
  end

  def create
    @group = Group.new(group_params)
    @group.seeking_gender = current_user.gender == "male" ? "female" : "male"
    @group.user_uids.each do |uid|
      @group.group_invites << GroupInvite.create(group: @group, user: User.from_provider_and_uid("facebook", uid))
    end

    if @group.save
      @group.users << current_user
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  private

  def group_params
    params.require(:group).permit(:admin_id, :tagline, :name, :gender, :location_id, :start_date, :end_date, interest_ids: [], user_uids: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_group = current_user.groups.find(params[:group_id])
    other_group = Group.find(params[:other_group_id])
    current_group.send("#{params[:group_action]}!", other_group)
    redirect_to root_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate_user!

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to user_path(user)
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/new.html.erb
<div class="row nmhxxs">
  <%= form_for @group do |f| %>
    <div class="col-md-8 col-md-offset-2 phxxs">
      <% if @group.errors.any? %>
        <div class="mts-plus">
          <%= @group.errors.full_messages.join(", ") %>
        </div>
      <% end %>
      <%= f.hidden_field :gender, value: current_user.gender %>
      <div class="row nmhxxs mts-plus">
        <div class="col-xs-4 phxxs fss lhs">
          Group Name
        </div>
        <div class="col-xs-8 phxxs">
          <%= f.text_field :name, class: "phxs pvxxxs bss bwam bc-dark-red full-width" %>
        </div>
      </div>
      <div class="row nmhxxs mts-plus">
        <div class="col-xs-4 phxxs fss lhs">
          Group Tagline
        </div>
        <div class="col-xs-8 phxxs">
          <%= f.text_field :tagline, class: "phxs pvxxxs bss bwam bc-dark-red full-width" %>
        </div>
      </div>
      <div class="row nmhxxs mts-plus js-users">
        <% @group.user_uids.each do |uid| %>
          <div class="col-xs-4 phxxs js-user">
            <img class="img-responsive" src="https://graph.facebook.com/<%= uid %>/picture?width=300&height=300"/>
            <input type="hidden" name="group[user_uids][]" value="<%= uid %>"/>
          </div>
        <% end %>
      </div>
      <div class="mts-plus js-add-users">
        <div class="phxs pvxxxs c-red fsxl fwl bras bss bwam bc-red pointer text-center full-width">
          <i class="fa fa-plus"></i> Add Friends
        </div>
      </div>
      <div class="row nmhxxs mts-plus">
        <div class="mts">
          <div class="col-xs-4 phxxs">
            <div class="row nmhxxs">
              <div class="col-sm-4 phxxs fsxxs">
                Visiting
              </div>
              <div class="col-sm-8 phxxs">
                <%= f.select :location_id, Location.order("city asc").map { |location| [location.city, location.id] }, { prompt: "location" }, class: "phxs pvxxxs bss bwas bc-12 full-width" %>
              </div>
            </div>
          </div>
          <div class="col-xs-4 phxxs">
            <div class="row nmhxxs">
              <div class="col-sm-4 phxxs fsxxs">
                From
              </div>
              <div class="col-sm-8 phxxs">
                <input type="text" class="phxs pvxxxs bss bwam bc-dark-red full-width js-datepicker" value="<%= @group.start_date.strftime("%m/%d/%Y") if @group.start_date.present? %>">
                <%= f.hidden_field :start_date %>
              </div>
            </div>
          </div>
          <div class="col-xs-4 phxxs">
            <div class="row nmhxxs">
              <div class="col-sm-4 phxxs fsxxs">
                To
              </div>
              <div class="col-sm-8 phxxs">
                <input type="text" class="phxs pvxxxs bss bwam bc-dark-red full-width js-datepicker" value="<%= @group.end_date.strftime("%m/%d/%Y") if @group.end_date.present? %>">
                <%= f.hidden_field :end_date %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row nmhxxs mtm">
        <% Interest.where(location_id: 1).each do |interest| %>
          <div class="col-sm-6 phxxs mtxs fsxs">
            <label>
              <%= check_box_tag "group[interest_ids][]", interest.id, @group.interest_ids.include?(interest.id) %>
              <%= interest.name %>
            </label>
          </div>
        <% end %>
      </div>
      <%= f.submit "Create Group", class: "mtxl phxs pvxxxs bg-red c-14 c-16-hover fsxl fwl bras full-width" %>
    </div>
  <% end %>
</div>

<script>
  var user_uids = "<%= @group.user_uids.to_json %>";
  $(function() {
    $(".js-add-users").click(function() {
      FB.ui({method: 'apprequests',
        message: 'SUP'
      }, function(response) {
        $.each(response.to, function() {
          FB.api("/" + this, function(user) {
            if (user_uids.indexOf(user.id) == -1) {
              $(".js-users").append("<div class='col-xs-4 phxxs js-user'><img class='img-responsive' src='https://graph.facebook.com/" + user.id + "/picture?width=300&height=300'/><input type='hidden' name='group[user_uids][]' value='" + user.id + "'/></div>");
              user_uids.push(user.id);
            }
          })
        });
      });
    });
    $(".js-datepicker").each(function() {
      $(this).datepicker({
        minDate: 1,
        altFormat: "yy/mm/dd",
        dateFormat: "mm/dd/yy",
        altField: $(this).next()
      });
    });
  });
</script>

app/views/groups/show.html.erb
<div class="row nmhxxs">
  <div class="col-sm-8 col-sm-offset-2 phxxs">
    <div class="fsxl fwxl c-red text-center"><%= @group.name %></div>
    <div class="fss c-red text-center"><%= @group.tagline %></div>
    <div class="row nmhxxs mtm">
      <% @group.users.each do |user| %>
        <div class="col-xs-4 phxxs mts">
          <%= image_tag user.profile_picture_large, class: "img-responsive bras" %>
        </div>
      <% end %>
      <% @group.group_invites.each do |group_invite| %>
        <div class="col-xs-4 phxxs mts">
          <%= image_tag group_invite.user.profile_picture_large, class: "img-responsive bras fade-m" %>
        </div>
      <% end %>
    </div>
    <table class="mtxl mha">
      <tr>
        <td class="phxs fss fwxl c-red">
          <%= @group.location.city %>
        </td>
        <td class="phxxxs fss c-dark-red">
          <%= @group.start_date.strftime("%m/%d/%y") %>
        </td>
        <td class="phxxxs fss c-dark-red">
          &mdash;
        </td>
        <td class="phxxxs fss c-dark-red">
          <%= @group.end_date.strftime("%m/%d/%y") %>
        </td>
      </tr>
    </table>
    <div class="row nmhxxs mtxl">
      <% @group.interests.each do |interest| %>
        <div class="col-xs-6 phxxs mtxs">
          <table class="full-width">
            <tr>
              <td class="dhxs" valign="top">
                <div class="daxs bg-red braxs"></div>
              </td>
              <td class="plxs" valign="top">
                <div class="fss c-0">
                  <%= interest.name %>
                </div>
              </td>
            </tr>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="row nmhxxs mtxl">
  <div class="col-sm-6 col-sm-offset-3 phxxs">
    <%= link_to new_group_path do %>
      <div class="bras bss bwam bc-dark-red bc-red-hover c-dark-red c-red-hover fsxl fwl dvxl lhxl">
        <div class="text-center">
          Start finding other groups <i class="relative mlxs fa fa-chevron-right lhxl"></i>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  Signed in as <strong><%= current_user.name %></strong>!
  <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <%= image_tag current_user.profile_picture %>
</div>
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <%= link_to new_group_path do %>
      <div class="btn btn-success full-width">Create Group</div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="bg-red dvl bss bwbm bc-dark-red">
  <div class="container phs full-height">
    <div class="pull-right lhl">
      <i class="fa fa-bars fsxxl lhl c-16"></i>
    </div>
    <table class="full-height">
      <tr>
        <td>
          <%= link_to current_user ? user_path(current_user) : root_path do %>
            <%= image_tag "navlogo.png", class: "dvs" %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Krew</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '<%= ENV["FACEBOOK_APP_ID"] %>',
        status     : true,
        xfbml      : true
      });

      // FB.api(
      //   "/{friendlist-id}",
      //   function (response) {
      //     if (response && !response.error) {
      //       /* handle the result */
      //     }
      //   }
      // );
    };

    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/all.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
  </script>
  <%= render partial: "layouts/navbar" %>
  <div class="container phxs mtm">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/show.html.erb
<div class="row nmhxxs">
  <div class="col-sm-8 col-sm-offset-2 phxxs">
    <%= link_to new_group_path do %>
      <div class="relative bras bss bwam bc-dark-red bc-red-hover c-dark-red c-red-hover fsxl fwl dvl lhl">
        <div class="absolute left mlxs">
          <i class="fa fa-plus fsxxl lhl"></i>
        </div>
        <div class="text-center">
          Create a Group
        </div>
      </div>
    <% end %>
    <div class="row nmhxs">
      <div class="col-xs-6 phxs mtl">
        <%= image_tag @user.profile_picture_large, class: "img-responsive bras" %>
      </div>
      <div class="col-xs-6 phxs mtl">
        <div class="mtxxxs-plus fwxl">
          <%= @user.name %>
        </div>
        <div class="mtxxxs-plus">
          <%= @user.location %>
        </div>
        <div class="mtxxxs-plus">
          <%= @user.available_text %>
        </div>
      </div>
    </div>
  </div>
</div>